// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/user-activity-tracking-go/internal/model"
	"github.com/Hidayathamir/user-activity-tracking-go/internal/usecase/requestlog"
	"sync"
)

// Ensure, that RequestLogUsecaseMock does implement requestlog.RequestLogUsecase.
// If this is not the case, regenerate this file with moq.
var _ requestlog.RequestLogUsecase = &RequestLogUsecaseMock{}

// RequestLogUsecaseMock is a mock implementation of requestlog.RequestLogUsecase.
//
//	func TestSomethingThatUsesRequestLogUsecase(t *testing.T) {
//
//		// make and configure a mocked requestlog.RequestLogUsecase
//		mockedRequestLogUsecase := &RequestLogUsecaseMock{
//			BatchConsumeClientRequestLogEventFunc: func(ctx context.Context, req *model.ReqBatchConsumeClientRequestLogEvent) error {
//				panic("mock out the BatchConsumeClientRequestLogEvent method")
//			},
//			GetClientDailyRequestCountFunc: func(ctx context.Context, req *model.ReqGetClientDailyRequestCount) (*model.ResGetClientDailyRequestCount, error) {
//				panic("mock out the GetClientDailyRequestCount method")
//			},
//			GetTop3ClientRequestCount24HourFunc: func(ctx context.Context, req *model.ReqGetTop3ClientRequestCount24Hour) (*model.ResGetTop3ClientRequestCount24Hour, error) {
//				panic("mock out the GetTop3ClientRequestCount24Hour method")
//			},
//			RecordAPIHitFunc: func(ctx context.Context, req *model.ReqRecordAPIHit) (*model.ResRecordAPIHit, error) {
//				panic("mock out the RecordAPIHit method")
//			},
//		}
//
//		// use mockedRequestLogUsecase in code that requires requestlog.RequestLogUsecase
//		// and then make assertions.
//
//	}
type RequestLogUsecaseMock struct {
	// BatchConsumeClientRequestLogEventFunc mocks the BatchConsumeClientRequestLogEvent method.
	BatchConsumeClientRequestLogEventFunc func(ctx context.Context, req *model.ReqBatchConsumeClientRequestLogEvent) error

	// GetClientDailyRequestCountFunc mocks the GetClientDailyRequestCount method.
	GetClientDailyRequestCountFunc func(ctx context.Context, req *model.ReqGetClientDailyRequestCount) (*model.ResGetClientDailyRequestCount, error)

	// GetTop3ClientRequestCount24HourFunc mocks the GetTop3ClientRequestCount24Hour method.
	GetTop3ClientRequestCount24HourFunc func(ctx context.Context, req *model.ReqGetTop3ClientRequestCount24Hour) (*model.ResGetTop3ClientRequestCount24Hour, error)

	// RecordAPIHitFunc mocks the RecordAPIHit method.
	RecordAPIHitFunc func(ctx context.Context, req *model.ReqRecordAPIHit) (*model.ResRecordAPIHit, error)

	// calls tracks calls to the methods.
	calls struct {
		// BatchConsumeClientRequestLogEvent holds details about calls to the BatchConsumeClientRequestLogEvent method.
		BatchConsumeClientRequestLogEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.ReqBatchConsumeClientRequestLogEvent
		}
		// GetClientDailyRequestCount holds details about calls to the GetClientDailyRequestCount method.
		GetClientDailyRequestCount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.ReqGetClientDailyRequestCount
		}
		// GetTop3ClientRequestCount24Hour holds details about calls to the GetTop3ClientRequestCount24Hour method.
		GetTop3ClientRequestCount24Hour []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.ReqGetTop3ClientRequestCount24Hour
		}
		// RecordAPIHit holds details about calls to the RecordAPIHit method.
		RecordAPIHit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.ReqRecordAPIHit
		}
	}
	lockBatchConsumeClientRequestLogEvent sync.RWMutex
	lockGetClientDailyRequestCount        sync.RWMutex
	lockGetTop3ClientRequestCount24Hour   sync.RWMutex
	lockRecordAPIHit                      sync.RWMutex
}

// BatchConsumeClientRequestLogEvent calls BatchConsumeClientRequestLogEventFunc.
func (mock *RequestLogUsecaseMock) BatchConsumeClientRequestLogEvent(ctx context.Context, req *model.ReqBatchConsumeClientRequestLogEvent) error {
	if mock.BatchConsumeClientRequestLogEventFunc == nil {
		panic("RequestLogUsecaseMock.BatchConsumeClientRequestLogEventFunc: method is nil but RequestLogUsecase.BatchConsumeClientRequestLogEvent was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.ReqBatchConsumeClientRequestLogEvent
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockBatchConsumeClientRequestLogEvent.Lock()
	mock.calls.BatchConsumeClientRequestLogEvent = append(mock.calls.BatchConsumeClientRequestLogEvent, callInfo)
	mock.lockBatchConsumeClientRequestLogEvent.Unlock()
	return mock.BatchConsumeClientRequestLogEventFunc(ctx, req)
}

// BatchConsumeClientRequestLogEventCalls gets all the calls that were made to BatchConsumeClientRequestLogEvent.
// Check the length with:
//
//	len(mockedRequestLogUsecase.BatchConsumeClientRequestLogEventCalls())
func (mock *RequestLogUsecaseMock) BatchConsumeClientRequestLogEventCalls() []struct {
	Ctx context.Context
	Req *model.ReqBatchConsumeClientRequestLogEvent
} {
	var calls []struct {
		Ctx context.Context
		Req *model.ReqBatchConsumeClientRequestLogEvent
	}
	mock.lockBatchConsumeClientRequestLogEvent.RLock()
	calls = mock.calls.BatchConsumeClientRequestLogEvent
	mock.lockBatchConsumeClientRequestLogEvent.RUnlock()
	return calls
}

// GetClientDailyRequestCount calls GetClientDailyRequestCountFunc.
func (mock *RequestLogUsecaseMock) GetClientDailyRequestCount(ctx context.Context, req *model.ReqGetClientDailyRequestCount) (*model.ResGetClientDailyRequestCount, error) {
	if mock.GetClientDailyRequestCountFunc == nil {
		panic("RequestLogUsecaseMock.GetClientDailyRequestCountFunc: method is nil but RequestLogUsecase.GetClientDailyRequestCount was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.ReqGetClientDailyRequestCount
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockGetClientDailyRequestCount.Lock()
	mock.calls.GetClientDailyRequestCount = append(mock.calls.GetClientDailyRequestCount, callInfo)
	mock.lockGetClientDailyRequestCount.Unlock()
	return mock.GetClientDailyRequestCountFunc(ctx, req)
}

// GetClientDailyRequestCountCalls gets all the calls that were made to GetClientDailyRequestCount.
// Check the length with:
//
//	len(mockedRequestLogUsecase.GetClientDailyRequestCountCalls())
func (mock *RequestLogUsecaseMock) GetClientDailyRequestCountCalls() []struct {
	Ctx context.Context
	Req *model.ReqGetClientDailyRequestCount
} {
	var calls []struct {
		Ctx context.Context
		Req *model.ReqGetClientDailyRequestCount
	}
	mock.lockGetClientDailyRequestCount.RLock()
	calls = mock.calls.GetClientDailyRequestCount
	mock.lockGetClientDailyRequestCount.RUnlock()
	return calls
}

// GetTop3ClientRequestCount24Hour calls GetTop3ClientRequestCount24HourFunc.
func (mock *RequestLogUsecaseMock) GetTop3ClientRequestCount24Hour(ctx context.Context, req *model.ReqGetTop3ClientRequestCount24Hour) (*model.ResGetTop3ClientRequestCount24Hour, error) {
	if mock.GetTop3ClientRequestCount24HourFunc == nil {
		panic("RequestLogUsecaseMock.GetTop3ClientRequestCount24HourFunc: method is nil but RequestLogUsecase.GetTop3ClientRequestCount24Hour was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.ReqGetTop3ClientRequestCount24Hour
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockGetTop3ClientRequestCount24Hour.Lock()
	mock.calls.GetTop3ClientRequestCount24Hour = append(mock.calls.GetTop3ClientRequestCount24Hour, callInfo)
	mock.lockGetTop3ClientRequestCount24Hour.Unlock()
	return mock.GetTop3ClientRequestCount24HourFunc(ctx, req)
}

// GetTop3ClientRequestCount24HourCalls gets all the calls that were made to GetTop3ClientRequestCount24Hour.
// Check the length with:
//
//	len(mockedRequestLogUsecase.GetTop3ClientRequestCount24HourCalls())
func (mock *RequestLogUsecaseMock) GetTop3ClientRequestCount24HourCalls() []struct {
	Ctx context.Context
	Req *model.ReqGetTop3ClientRequestCount24Hour
} {
	var calls []struct {
		Ctx context.Context
		Req *model.ReqGetTop3ClientRequestCount24Hour
	}
	mock.lockGetTop3ClientRequestCount24Hour.RLock()
	calls = mock.calls.GetTop3ClientRequestCount24Hour
	mock.lockGetTop3ClientRequestCount24Hour.RUnlock()
	return calls
}

// RecordAPIHit calls RecordAPIHitFunc.
func (mock *RequestLogUsecaseMock) RecordAPIHit(ctx context.Context, req *model.ReqRecordAPIHit) (*model.ResRecordAPIHit, error) {
	if mock.RecordAPIHitFunc == nil {
		panic("RequestLogUsecaseMock.RecordAPIHitFunc: method is nil but RequestLogUsecase.RecordAPIHit was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.ReqRecordAPIHit
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockRecordAPIHit.Lock()
	mock.calls.RecordAPIHit = append(mock.calls.RecordAPIHit, callInfo)
	mock.lockRecordAPIHit.Unlock()
	return mock.RecordAPIHitFunc(ctx, req)
}

// RecordAPIHitCalls gets all the calls that were made to RecordAPIHit.
// Check the length with:
//
//	len(mockedRequestLogUsecase.RecordAPIHitCalls())
func (mock *RequestLogUsecaseMock) RecordAPIHitCalls() []struct {
	Ctx context.Context
	Req *model.ReqRecordAPIHit
} {
	var calls []struct {
		Ctx context.Context
		Req *model.ReqRecordAPIHit
	}
	mock.lockRecordAPIHit.RLock()
	calls = mock.calls.RecordAPIHit
	mock.lockRecordAPIHit.RUnlock()
	return calls
}
