// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/user-activity-tracking-go/internal/model"
	"github.com/Hidayathamir/user-activity-tracking-go/internal/usecase/client"
	"sync"
)

// Ensure, that ClientUsecaseMock does implement client.ClientUsecase.
// If this is not the case, regenerate this file with moq.
var _ client.ClientUsecase = &ClientUsecaseMock{}

// ClientUsecaseMock is a mock implementation of client.ClientUsecase.
//
//	func TestSomethingThatUsesClientUsecase(t *testing.T) {
//
//		// make and configure a mocked client.ClientUsecase
//		mockedClientUsecase := &ClientUsecaseMock{
//			GetClientDetailFunc: func(ctx context.Context, req *model.ReqGetClientDetail) (*model.ResGetClientDetail, error) {
//				panic("mock out the GetClientDetail method")
//			},
//			LoginFunc: func(ctx context.Context, req *model.ReqLogin) (*model.ResLogin, error) {
//				panic("mock out the Login method")
//			},
//			RegisterFunc: func(ctx context.Context, req *model.ReqRegister) (*model.ResRegister, error) {
//				panic("mock out the Register method")
//			},
//			VerifyFunc: func(ctx context.Context, req *model.ReqVerify) (*model.ClientAuth, error) {
//				panic("mock out the Verify method")
//			},
//		}
//
//		// use mockedClientUsecase in code that requires client.ClientUsecase
//		// and then make assertions.
//
//	}
type ClientUsecaseMock struct {
	// GetClientDetailFunc mocks the GetClientDetail method.
	GetClientDetailFunc func(ctx context.Context, req *model.ReqGetClientDetail) (*model.ResGetClientDetail, error)

	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context, req *model.ReqLogin) (*model.ResLogin, error)

	// RegisterFunc mocks the Register method.
	RegisterFunc func(ctx context.Context, req *model.ReqRegister) (*model.ResRegister, error)

	// VerifyFunc mocks the Verify method.
	VerifyFunc func(ctx context.Context, req *model.ReqVerify) (*model.ClientAuth, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetClientDetail holds details about calls to the GetClientDetail method.
		GetClientDetail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.ReqGetClientDetail
		}
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.ReqLogin
		}
		// Register holds details about calls to the Register method.
		Register []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.ReqRegister
		}
		// Verify holds details about calls to the Verify method.
		Verify []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.ReqVerify
		}
	}
	lockGetClientDetail sync.RWMutex
	lockLogin           sync.RWMutex
	lockRegister        sync.RWMutex
	lockVerify          sync.RWMutex
}

// GetClientDetail calls GetClientDetailFunc.
func (mock *ClientUsecaseMock) GetClientDetail(ctx context.Context, req *model.ReqGetClientDetail) (*model.ResGetClientDetail, error) {
	if mock.GetClientDetailFunc == nil {
		panic("ClientUsecaseMock.GetClientDetailFunc: method is nil but ClientUsecase.GetClientDetail was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.ReqGetClientDetail
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockGetClientDetail.Lock()
	mock.calls.GetClientDetail = append(mock.calls.GetClientDetail, callInfo)
	mock.lockGetClientDetail.Unlock()
	return mock.GetClientDetailFunc(ctx, req)
}

// GetClientDetailCalls gets all the calls that were made to GetClientDetail.
// Check the length with:
//
//	len(mockedClientUsecase.GetClientDetailCalls())
func (mock *ClientUsecaseMock) GetClientDetailCalls() []struct {
	Ctx context.Context
	Req *model.ReqGetClientDetail
} {
	var calls []struct {
		Ctx context.Context
		Req *model.ReqGetClientDetail
	}
	mock.lockGetClientDetail.RLock()
	calls = mock.calls.GetClientDetail
	mock.lockGetClientDetail.RUnlock()
	return calls
}

// Login calls LoginFunc.
func (mock *ClientUsecaseMock) Login(ctx context.Context, req *model.ReqLogin) (*model.ResLogin, error) {
	if mock.LoginFunc == nil {
		panic("ClientUsecaseMock.LoginFunc: method is nil but ClientUsecase.Login was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.ReqLogin
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(ctx, req)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedClientUsecase.LoginCalls())
func (mock *ClientUsecaseMock) LoginCalls() []struct {
	Ctx context.Context
	Req *model.ReqLogin
} {
	var calls []struct {
		Ctx context.Context
		Req *model.ReqLogin
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}

// Register calls RegisterFunc.
func (mock *ClientUsecaseMock) Register(ctx context.Context, req *model.ReqRegister) (*model.ResRegister, error) {
	if mock.RegisterFunc == nil {
		panic("ClientUsecaseMock.RegisterFunc: method is nil but ClientUsecase.Register was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.ReqRegister
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockRegister.Lock()
	mock.calls.Register = append(mock.calls.Register, callInfo)
	mock.lockRegister.Unlock()
	return mock.RegisterFunc(ctx, req)
}

// RegisterCalls gets all the calls that were made to Register.
// Check the length with:
//
//	len(mockedClientUsecase.RegisterCalls())
func (mock *ClientUsecaseMock) RegisterCalls() []struct {
	Ctx context.Context
	Req *model.ReqRegister
} {
	var calls []struct {
		Ctx context.Context
		Req *model.ReqRegister
	}
	mock.lockRegister.RLock()
	calls = mock.calls.Register
	mock.lockRegister.RUnlock()
	return calls
}

// Verify calls VerifyFunc.
func (mock *ClientUsecaseMock) Verify(ctx context.Context, req *model.ReqVerify) (*model.ClientAuth, error) {
	if mock.VerifyFunc == nil {
		panic("ClientUsecaseMock.VerifyFunc: method is nil but ClientUsecase.Verify was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.ReqVerify
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockVerify.Lock()
	mock.calls.Verify = append(mock.calls.Verify, callInfo)
	mock.lockVerify.Unlock()
	return mock.VerifyFunc(ctx, req)
}

// VerifyCalls gets all the calls that were made to Verify.
// Check the length with:
//
//	len(mockedClientUsecase.VerifyCalls())
func (mock *ClientUsecaseMock) VerifyCalls() []struct {
	Ctx context.Context
	Req *model.ReqVerify
} {
	var calls []struct {
		Ctx context.Context
		Req *model.ReqVerify
	}
	mock.lockVerify.RLock()
	calls = mock.calls.Verify
	mock.lockVerify.RUnlock()
	return calls
}
