// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/user-activity-tracking-go/internal/gateway/messaging"
	"github.com/Hidayathamir/user-activity-tracking-go/internal/model"
	"sync"
)

// Ensure, that ProducerMock does implement messaging.Producer.
// If this is not the case, regenerate this file with moq.
var _ messaging.Producer = &ProducerMock{}

// ProducerMock is a mock implementation of messaging.Producer.
//
//	func TestSomethingThatUsesProducer(t *testing.T) {
//
//		// make and configure a mocked messaging.Producer
//		mockedProducer := &ProducerMock{
//			SendClientRequestLogEventFunc: func(ctx context.Context, event *model.ClientRequestLogEvent) error {
//				panic("mock out the SendClientRequestLogEvent method")
//			},
//		}
//
//		// use mockedProducer in code that requires messaging.Producer
//		// and then make assertions.
//
//	}
type ProducerMock struct {
	// SendClientRequestLogEventFunc mocks the SendClientRequestLogEvent method.
	SendClientRequestLogEventFunc func(ctx context.Context, event *model.ClientRequestLogEvent) error

	// calls tracks calls to the methods.
	calls struct {
		// SendClientRequestLogEvent holds details about calls to the SendClientRequestLogEvent method.
		SendClientRequestLogEvent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Event is the event argument value.
			Event *model.ClientRequestLogEvent
		}
	}
	lockSendClientRequestLogEvent sync.RWMutex
}

// SendClientRequestLogEvent calls SendClientRequestLogEventFunc.
func (mock *ProducerMock) SendClientRequestLogEvent(ctx context.Context, event *model.ClientRequestLogEvent) error {
	if mock.SendClientRequestLogEventFunc == nil {
		panic("ProducerMock.SendClientRequestLogEventFunc: method is nil but Producer.SendClientRequestLogEvent was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Event *model.ClientRequestLogEvent
	}{
		Ctx:   ctx,
		Event: event,
	}
	mock.lockSendClientRequestLogEvent.Lock()
	mock.calls.SendClientRequestLogEvent = append(mock.calls.SendClientRequestLogEvent, callInfo)
	mock.lockSendClientRequestLogEvent.Unlock()
	return mock.SendClientRequestLogEventFunc(ctx, event)
}

// SendClientRequestLogEventCalls gets all the calls that were made to SendClientRequestLogEvent.
// Check the length with:
//
//	len(mockedProducer.SendClientRequestLogEventCalls())
func (mock *ProducerMock) SendClientRequestLogEventCalls() []struct {
	Ctx   context.Context
	Event *model.ClientRequestLogEvent
} {
	var calls []struct {
		Ctx   context.Context
		Event *model.ClientRequestLogEvent
	}
	mock.lockSendClientRequestLogEvent.RLock()
	calls = mock.calls.SendClientRequestLogEvent
	mock.lockSendClientRequestLogEvent.RUnlock()
	return calls
}
