// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/user-activity-tracking-go/internal/entity"
	"github.com/Hidayathamir/user-activity-tracking-go/internal/infra/repository"
	"gorm.io/gorm"
	"sync"
)

// Ensure, that ClientRepositoryMock does implement repository.ClientRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.ClientRepository = &ClientRepositoryMock{}

// ClientRepositoryMock is a mock implementation of repository.ClientRepository.
//
//	func TestSomethingThatUsesClientRepository(t *testing.T) {
//
//		// make and configure a mocked repository.ClientRepository
//		mockedClientRepository := &ClientRepositoryMock{
//			CreateFunc: func(ctx context.Context, db *gorm.DB, client *entity.Client) error {
//				panic("mock out the Create method")
//			},
//			FindByAPIKeyFunc: func(ctx context.Context, db *gorm.DB, client *entity.Client, apiKey string) error {
//				panic("mock out the FindByAPIKey method")
//			},
//			FindByNameFunc: func(ctx context.Context, db *gorm.DB, client *entity.Client, name string) error {
//				panic("mock out the FindByName method")
//			},
//		}
//
//		// use mockedClientRepository in code that requires repository.ClientRepository
//		// and then make assertions.
//
//	}
type ClientRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, db *gorm.DB, client *entity.Client) error

	// FindByAPIKeyFunc mocks the FindByAPIKey method.
	FindByAPIKeyFunc func(ctx context.Context, db *gorm.DB, client *entity.Client, apiKey string) error

	// FindByNameFunc mocks the FindByName method.
	FindByNameFunc func(ctx context.Context, db *gorm.DB, client *entity.Client, name string) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Client is the client argument value.
			Client *entity.Client
		}
		// FindByAPIKey holds details about calls to the FindByAPIKey method.
		FindByAPIKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Client is the client argument value.
			Client *entity.Client
			// ApiKey is the apiKey argument value.
			ApiKey string
		}
		// FindByName holds details about calls to the FindByName method.
		FindByName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Db is the db argument value.
			Db *gorm.DB
			// Client is the client argument value.
			Client *entity.Client
			// Name is the name argument value.
			Name string
		}
	}
	lockCreate       sync.RWMutex
	lockFindByAPIKey sync.RWMutex
	lockFindByName   sync.RWMutex
}

// Create calls CreateFunc.
func (mock *ClientRepositoryMock) Create(ctx context.Context, db *gorm.DB, client *entity.Client) error {
	if mock.CreateFunc == nil {
		panic("ClientRepositoryMock.CreateFunc: method is nil but ClientRepository.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Db     *gorm.DB
		Client *entity.Client
	}{
		Ctx:    ctx,
		Db:     db,
		Client: client,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, db, client)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedClientRepository.CreateCalls())
func (mock *ClientRepositoryMock) CreateCalls() []struct {
	Ctx    context.Context
	Db     *gorm.DB
	Client *entity.Client
} {
	var calls []struct {
		Ctx    context.Context
		Db     *gorm.DB
		Client *entity.Client
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// FindByAPIKey calls FindByAPIKeyFunc.
func (mock *ClientRepositoryMock) FindByAPIKey(ctx context.Context, db *gorm.DB, client *entity.Client, apiKey string) error {
	if mock.FindByAPIKeyFunc == nil {
		panic("ClientRepositoryMock.FindByAPIKeyFunc: method is nil but ClientRepository.FindByAPIKey was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Db     *gorm.DB
		Client *entity.Client
		ApiKey string
	}{
		Ctx:    ctx,
		Db:     db,
		Client: client,
		ApiKey: apiKey,
	}
	mock.lockFindByAPIKey.Lock()
	mock.calls.FindByAPIKey = append(mock.calls.FindByAPIKey, callInfo)
	mock.lockFindByAPIKey.Unlock()
	return mock.FindByAPIKeyFunc(ctx, db, client, apiKey)
}

// FindByAPIKeyCalls gets all the calls that were made to FindByAPIKey.
// Check the length with:
//
//	len(mockedClientRepository.FindByAPIKeyCalls())
func (mock *ClientRepositoryMock) FindByAPIKeyCalls() []struct {
	Ctx    context.Context
	Db     *gorm.DB
	Client *entity.Client
	ApiKey string
} {
	var calls []struct {
		Ctx    context.Context
		Db     *gorm.DB
		Client *entity.Client
		ApiKey string
	}
	mock.lockFindByAPIKey.RLock()
	calls = mock.calls.FindByAPIKey
	mock.lockFindByAPIKey.RUnlock()
	return calls
}

// FindByName calls FindByNameFunc.
func (mock *ClientRepositoryMock) FindByName(ctx context.Context, db *gorm.DB, client *entity.Client, name string) error {
	if mock.FindByNameFunc == nil {
		panic("ClientRepositoryMock.FindByNameFunc: method is nil but ClientRepository.FindByName was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Db     *gorm.DB
		Client *entity.Client
		Name   string
	}{
		Ctx:    ctx,
		Db:     db,
		Client: client,
		Name:   name,
	}
	mock.lockFindByName.Lock()
	mock.calls.FindByName = append(mock.calls.FindByName, callInfo)
	mock.lockFindByName.Unlock()
	return mock.FindByNameFunc(ctx, db, client, name)
}

// FindByNameCalls gets all the calls that were made to FindByName.
// Check the length with:
//
//	len(mockedClientRepository.FindByNameCalls())
func (mock *ClientRepositoryMock) FindByNameCalls() []struct {
	Ctx    context.Context
	Db     *gorm.DB
	Client *entity.Client
	Name   string
} {
	var calls []struct {
		Ctx    context.Context
		Db     *gorm.DB
		Client *entity.Client
		Name   string
	}
	mock.lockFindByName.RLock()
	calls = mock.calls.FindByName
	mock.lockFindByName.RUnlock()
	return calls
}
