// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/Hidayathamir/user-activity-tracking-go/internal/repository"
)

// Ensure, that ClientRequestCountRepositoryMock does implement repository.ClientRequestCountRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.ClientRequestCountRepository = &ClientRequestCountRepositoryMock{}

// ClientRequestCountRepositoryMock is a mock implementation of repository.ClientRequestCountRepository.
//
//	func TestSomethingThatUsesClientRequestCountRepository(t *testing.T) {
//
//		// make and configure a mocked repository.ClientRequestCountRepository
//		mockedClientRequestCountRepository := &ClientRequestCountRepositoryMock{
//		}
//
//		// use mockedClientRequestCountRepository in code that requires repository.ClientRequestCountRepository
//		// and then make assertions.
//
//	}
type ClientRequestCountRepositoryMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
