// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/user-activity-tracking-go/internal/model"
	"github.com/Hidayathamir/user-activity-tracking-go/internal/usecase/requestlog"
	"sync"
)

// Ensure, that RequestLogUsecaseMock does implement requestlog.RequestLogUsecase.
// If this is not the case, regenerate this file with moq.
var _ requestlog.RequestLogUsecase = &RequestLogUsecaseMock{}

// RequestLogUsecaseMock is a mock implementation of requestlog.RequestLogUsecase.
//
//	func TestSomethingThatUsesRequestLogUsecase(t *testing.T) {
//
//		// make and configure a mocked requestlog.RequestLogUsecase
//		mockedRequestLogUsecase := &RequestLogUsecaseMock{
//			RecordAPIHitFunc: func(ctx context.Context, req *model.ReqRecordAPIHit) (*model.ResRecordAPIHit, error) {
//				panic("mock out the RecordAPIHit method")
//			},
//		}
//
//		// use mockedRequestLogUsecase in code that requires requestlog.RequestLogUsecase
//		// and then make assertions.
//
//	}
type RequestLogUsecaseMock struct {
	// RecordAPIHitFunc mocks the RecordAPIHit method.
	RecordAPIHitFunc func(ctx context.Context, req *model.ReqRecordAPIHit) (*model.ResRecordAPIHit, error)

	// calls tracks calls to the methods.
	calls struct {
		// RecordAPIHit holds details about calls to the RecordAPIHit method.
		RecordAPIHit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *model.ReqRecordAPIHit
		}
	}
	lockRecordAPIHit sync.RWMutex
}

// RecordAPIHit calls RecordAPIHitFunc.
func (mock *RequestLogUsecaseMock) RecordAPIHit(ctx context.Context, req *model.ReqRecordAPIHit) (*model.ResRecordAPIHit, error) {
	if mock.RecordAPIHitFunc == nil {
		panic("RequestLogUsecaseMock.RecordAPIHitFunc: method is nil but RequestLogUsecase.RecordAPIHit was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *model.ReqRecordAPIHit
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockRecordAPIHit.Lock()
	mock.calls.RecordAPIHit = append(mock.calls.RecordAPIHit, callInfo)
	mock.lockRecordAPIHit.Unlock()
	return mock.RecordAPIHitFunc(ctx, req)
}

// RecordAPIHitCalls gets all the calls that were made to RecordAPIHit.
// Check the length with:
//
//	len(mockedRequestLogUsecase.RecordAPIHitCalls())
func (mock *RequestLogUsecaseMock) RecordAPIHitCalls() []struct {
	Ctx context.Context
	Req *model.ReqRecordAPIHit
} {
	var calls []struct {
		Ctx context.Context
		Req *model.ReqRecordAPIHit
	}
	mock.lockRecordAPIHit.RLock()
	calls = mock.calls.RecordAPIHit
	mock.lockRecordAPIHit.RUnlock()
	return calls
}
