// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"github.com/Hidayathamir/user-activity-tracking-go/internal/infra/cache"
	"github.com/Hidayathamir/user-activity-tracking-go/internal/model"
	"sync"
	"time"
)

// Ensure, that CacheMock does implement cache.Cache.
// If this is not the case, regenerate this file with moq.
var _ cache.Cache = &CacheMock{}

// CacheMock is a mock implementation of cache.Cache.
//
//	func TestSomethingThatUsesCache(t *testing.T) {
//
//		// make and configure a mocked cache.Cache
//		mockedCache := &CacheMock{
//			GetCountByAPIKeyAndDateFunc: func(ctx context.Context, apiKey string, datetime time.Time) (int, error) {
//				panic("mock out the GetCountByAPIKeyAndDate method")
//			},
//			GetTop3ClientRequestCount24HourFunc: func(ctx context.Context) (model.APIKeyCountList, error) {
//				panic("mock out the GetTop3ClientRequestCount24Hour method")
//			},
//			IncrementTopClientRequestCountHourlyFunc: func(ctx context.Context, timestamp time.Time, increment int, member string) error {
//				panic("mock out the IncrementTopClientRequestCountHourly method")
//			},
//			SetClientRequestCountFunc: func(ctx context.Context, apiKey string, datetime time.Time, value int, ttl time.Duration) error {
//				panic("mock out the SetClientRequestCount method")
//			},
//			SetClientRequestCountIfExistFunc: func(ctx context.Context, apiKey string, datetime time.Time, value int) error {
//				panic("mock out the SetClientRequestCountIfExist method")
//			},
//		}
//
//		// use mockedCache in code that requires cache.Cache
//		// and then make assertions.
//
//	}
type CacheMock struct {
	// GetCountByAPIKeyAndDateFunc mocks the GetCountByAPIKeyAndDate method.
	GetCountByAPIKeyAndDateFunc func(ctx context.Context, apiKey string, datetime time.Time) (int, error)

	// GetTop3ClientRequestCount24HourFunc mocks the GetTop3ClientRequestCount24Hour method.
	GetTop3ClientRequestCount24HourFunc func(ctx context.Context) (model.APIKeyCountList, error)

	// IncrementTopClientRequestCountHourlyFunc mocks the IncrementTopClientRequestCountHourly method.
	IncrementTopClientRequestCountHourlyFunc func(ctx context.Context, timestamp time.Time, increment int, member string) error

	// SetClientRequestCountFunc mocks the SetClientRequestCount method.
	SetClientRequestCountFunc func(ctx context.Context, apiKey string, datetime time.Time, value int, ttl time.Duration) error

	// SetClientRequestCountIfExistFunc mocks the SetClientRequestCountIfExist method.
	SetClientRequestCountIfExistFunc func(ctx context.Context, apiKey string, datetime time.Time, value int) error

	// calls tracks calls to the methods.
	calls struct {
		// GetCountByAPIKeyAndDate holds details about calls to the GetCountByAPIKeyAndDate method.
		GetCountByAPIKeyAndDate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ApiKey is the apiKey argument value.
			ApiKey string
			// Datetime is the datetime argument value.
			Datetime time.Time
		}
		// GetTop3ClientRequestCount24Hour holds details about calls to the GetTop3ClientRequestCount24Hour method.
		GetTop3ClientRequestCount24Hour []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// IncrementTopClientRequestCountHourly holds details about calls to the IncrementTopClientRequestCountHourly method.
		IncrementTopClientRequestCountHourly []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Timestamp is the timestamp argument value.
			Timestamp time.Time
			// Increment is the increment argument value.
			Increment int
			// Member is the member argument value.
			Member string
		}
		// SetClientRequestCount holds details about calls to the SetClientRequestCount method.
		SetClientRequestCount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ApiKey is the apiKey argument value.
			ApiKey string
			// Datetime is the datetime argument value.
			Datetime time.Time
			// Value is the value argument value.
			Value int
			// TTL is the ttl argument value.
			TTL time.Duration
		}
		// SetClientRequestCountIfExist holds details about calls to the SetClientRequestCountIfExist method.
		SetClientRequestCountIfExist []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ApiKey is the apiKey argument value.
			ApiKey string
			// Datetime is the datetime argument value.
			Datetime time.Time
			// Value is the value argument value.
			Value int
		}
	}
	lockGetCountByAPIKeyAndDate              sync.RWMutex
	lockGetTop3ClientRequestCount24Hour      sync.RWMutex
	lockIncrementTopClientRequestCountHourly sync.RWMutex
	lockSetClientRequestCount                sync.RWMutex
	lockSetClientRequestCountIfExist         sync.RWMutex
}

// GetCountByAPIKeyAndDate calls GetCountByAPIKeyAndDateFunc.
func (mock *CacheMock) GetCountByAPIKeyAndDate(ctx context.Context, apiKey string, datetime time.Time) (int, error) {
	if mock.GetCountByAPIKeyAndDateFunc == nil {
		panic("CacheMock.GetCountByAPIKeyAndDateFunc: method is nil but Cache.GetCountByAPIKeyAndDate was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ApiKey   string
		Datetime time.Time
	}{
		Ctx:      ctx,
		ApiKey:   apiKey,
		Datetime: datetime,
	}
	mock.lockGetCountByAPIKeyAndDate.Lock()
	mock.calls.GetCountByAPIKeyAndDate = append(mock.calls.GetCountByAPIKeyAndDate, callInfo)
	mock.lockGetCountByAPIKeyAndDate.Unlock()
	return mock.GetCountByAPIKeyAndDateFunc(ctx, apiKey, datetime)
}

// GetCountByAPIKeyAndDateCalls gets all the calls that were made to GetCountByAPIKeyAndDate.
// Check the length with:
//
//	len(mockedCache.GetCountByAPIKeyAndDateCalls())
func (mock *CacheMock) GetCountByAPIKeyAndDateCalls() []struct {
	Ctx      context.Context
	ApiKey   string
	Datetime time.Time
} {
	var calls []struct {
		Ctx      context.Context
		ApiKey   string
		Datetime time.Time
	}
	mock.lockGetCountByAPIKeyAndDate.RLock()
	calls = mock.calls.GetCountByAPIKeyAndDate
	mock.lockGetCountByAPIKeyAndDate.RUnlock()
	return calls
}

// GetTop3ClientRequestCount24Hour calls GetTop3ClientRequestCount24HourFunc.
func (mock *CacheMock) GetTop3ClientRequestCount24Hour(ctx context.Context) (model.APIKeyCountList, error) {
	if mock.GetTop3ClientRequestCount24HourFunc == nil {
		panic("CacheMock.GetTop3ClientRequestCount24HourFunc: method is nil but Cache.GetTop3ClientRequestCount24Hour was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetTop3ClientRequestCount24Hour.Lock()
	mock.calls.GetTop3ClientRequestCount24Hour = append(mock.calls.GetTop3ClientRequestCount24Hour, callInfo)
	mock.lockGetTop3ClientRequestCount24Hour.Unlock()
	return mock.GetTop3ClientRequestCount24HourFunc(ctx)
}

// GetTop3ClientRequestCount24HourCalls gets all the calls that were made to GetTop3ClientRequestCount24Hour.
// Check the length with:
//
//	len(mockedCache.GetTop3ClientRequestCount24HourCalls())
func (mock *CacheMock) GetTop3ClientRequestCount24HourCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetTop3ClientRequestCount24Hour.RLock()
	calls = mock.calls.GetTop3ClientRequestCount24Hour
	mock.lockGetTop3ClientRequestCount24Hour.RUnlock()
	return calls
}

// IncrementTopClientRequestCountHourly calls IncrementTopClientRequestCountHourlyFunc.
func (mock *CacheMock) IncrementTopClientRequestCountHourly(ctx context.Context, timestamp time.Time, increment int, member string) error {
	if mock.IncrementTopClientRequestCountHourlyFunc == nil {
		panic("CacheMock.IncrementTopClientRequestCountHourlyFunc: method is nil but Cache.IncrementTopClientRequestCountHourly was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Timestamp time.Time
		Increment int
		Member    string
	}{
		Ctx:       ctx,
		Timestamp: timestamp,
		Increment: increment,
		Member:    member,
	}
	mock.lockIncrementTopClientRequestCountHourly.Lock()
	mock.calls.IncrementTopClientRequestCountHourly = append(mock.calls.IncrementTopClientRequestCountHourly, callInfo)
	mock.lockIncrementTopClientRequestCountHourly.Unlock()
	return mock.IncrementTopClientRequestCountHourlyFunc(ctx, timestamp, increment, member)
}

// IncrementTopClientRequestCountHourlyCalls gets all the calls that were made to IncrementTopClientRequestCountHourly.
// Check the length with:
//
//	len(mockedCache.IncrementTopClientRequestCountHourlyCalls())
func (mock *CacheMock) IncrementTopClientRequestCountHourlyCalls() []struct {
	Ctx       context.Context
	Timestamp time.Time
	Increment int
	Member    string
} {
	var calls []struct {
		Ctx       context.Context
		Timestamp time.Time
		Increment int
		Member    string
	}
	mock.lockIncrementTopClientRequestCountHourly.RLock()
	calls = mock.calls.IncrementTopClientRequestCountHourly
	mock.lockIncrementTopClientRequestCountHourly.RUnlock()
	return calls
}

// SetClientRequestCount calls SetClientRequestCountFunc.
func (mock *CacheMock) SetClientRequestCount(ctx context.Context, apiKey string, datetime time.Time, value int, ttl time.Duration) error {
	if mock.SetClientRequestCountFunc == nil {
		panic("CacheMock.SetClientRequestCountFunc: method is nil but Cache.SetClientRequestCount was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ApiKey   string
		Datetime time.Time
		Value    int
		TTL      time.Duration
	}{
		Ctx:      ctx,
		ApiKey:   apiKey,
		Datetime: datetime,
		Value:    value,
		TTL:      ttl,
	}
	mock.lockSetClientRequestCount.Lock()
	mock.calls.SetClientRequestCount = append(mock.calls.SetClientRequestCount, callInfo)
	mock.lockSetClientRequestCount.Unlock()
	return mock.SetClientRequestCountFunc(ctx, apiKey, datetime, value, ttl)
}

// SetClientRequestCountCalls gets all the calls that were made to SetClientRequestCount.
// Check the length with:
//
//	len(mockedCache.SetClientRequestCountCalls())
func (mock *CacheMock) SetClientRequestCountCalls() []struct {
	Ctx      context.Context
	ApiKey   string
	Datetime time.Time
	Value    int
	TTL      time.Duration
} {
	var calls []struct {
		Ctx      context.Context
		ApiKey   string
		Datetime time.Time
		Value    int
		TTL      time.Duration
	}
	mock.lockSetClientRequestCount.RLock()
	calls = mock.calls.SetClientRequestCount
	mock.lockSetClientRequestCount.RUnlock()
	return calls
}

// SetClientRequestCountIfExist calls SetClientRequestCountIfExistFunc.
func (mock *CacheMock) SetClientRequestCountIfExist(ctx context.Context, apiKey string, datetime time.Time, value int) error {
	if mock.SetClientRequestCountIfExistFunc == nil {
		panic("CacheMock.SetClientRequestCountIfExistFunc: method is nil but Cache.SetClientRequestCountIfExist was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ApiKey   string
		Datetime time.Time
		Value    int
	}{
		Ctx:      ctx,
		ApiKey:   apiKey,
		Datetime: datetime,
		Value:    value,
	}
	mock.lockSetClientRequestCountIfExist.Lock()
	mock.calls.SetClientRequestCountIfExist = append(mock.calls.SetClientRequestCountIfExist, callInfo)
	mock.lockSetClientRequestCountIfExist.Unlock()
	return mock.SetClientRequestCountIfExistFunc(ctx, apiKey, datetime, value)
}

// SetClientRequestCountIfExistCalls gets all the calls that were made to SetClientRequestCountIfExist.
// Check the length with:
//
//	len(mockedCache.SetClientRequestCountIfExistCalls())
func (mock *CacheMock) SetClientRequestCountIfExistCalls() []struct {
	Ctx      context.Context
	ApiKey   string
	Datetime time.Time
	Value    int
} {
	var calls []struct {
		Ctx      context.Context
		ApiKey   string
		Datetime time.Time
		Value    int
	}
	mock.lockSetClientRequestCountIfExist.RLock()
	calls = mock.calls.SetClientRequestCountIfExist
	mock.lockSetClientRequestCountIfExist.RUnlock()
	return calls
}
