// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/Hidayathamir/user-activity-tracking-go/internal/cache"
)

// Ensure, that CacheMock does implement cache.Cache.
// If this is not the case, regenerate this file with moq.
var _ cache.Cache = &CacheMock{}

// CacheMock is a mock implementation of cache.Cache.
//
//	func TestSomethingThatUsesCache(t *testing.T) {
//
//		// make and configure a mocked cache.Cache
//		mockedCache := &CacheMock{
//		}
//
//		// use mockedCache in code that requires cache.Cache
//		// and then make assertions.
//
//	}
type CacheMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
