// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/Hidayathamir/user-activity-tracking-go/internal/repository"
)

// Ensure, that RequestLogRepositoryMock does implement repository.RequestLogRepository.
// If this is not the case, regenerate this file with moq.
var _ repository.RequestLogRepository = &RequestLogRepositoryMock{}

// RequestLogRepositoryMock is a mock implementation of repository.RequestLogRepository.
//
//	func TestSomethingThatUsesRequestLogRepository(t *testing.T) {
//
//		// make and configure a mocked repository.RequestLogRepository
//		mockedRequestLogRepository := &RequestLogRepositoryMock{
//		}
//
//		// use mockedRequestLogRepository in code that requires repository.RequestLogRepository
//		// and then make assertions.
//
//	}
type RequestLogRepositoryMock struct {
	// calls tracks calls to the methods.
	calls struct {
	}
}
